---
- name: Install dotnet sdk
  apt:
    name: dotnet-sdk-8.0
    state: present

- name: Clean up frontend exposed html directory
  shell: rm -rf "{{ backend_root_dir }}/*" "{{ backend_root_dir }}/.*"

- name: Copy dotnet application to organized directory
  ansible.posix.synchronize:
    src: "{{ role_path }}/files/{{backend_dir_name}}/"
    dest: "{{ backend_root_dir }}/"

- name: Read appsettings
  ansible.builtin.set_fact:
    jsondata: "{{ lookup('file', backend_root_dir+'/'+backend_appsettings_file) }}"
    
- name: Update appsettings in regards to chosen database engine before
  ansible.utils.update_fact:
    updates:
      - path: jsondata.ConnectionStrings.Postgres
        value: "Host={{ database_server }}; Database={{ database_name }}; Username={{ database_user }}; Password={{ database_password }}"
  register: updated_appsettings

- name: Save appsettings
  copy: 
    content: "{{ updated_appsettings | to_nice_json }}" 
    dest: "{{ backend_root_dir }}/{{ backend_appsettings_file }}"

- name: Generate backend service
  ansible.builtin.template:
    src: "{{ role_path }}/templates/app.service.j2"
    dest: "{{ services_path }}/{{ backend_service_name }}.service"
    mode: "0755"

- name: Enable api backend service to be started every time after reboot
  ansible.builtin.systemd_service:
    name: "{{ backend_service_name }}"
    enabled: true

- name: Start service httpd, if not started
  ansible.builtin.service:
    name: "{{ backend_service_name }}"
    state: started
